"""Assemble xlsr_features.npz from the SSL branch's embedding cache.

The SSL branch caches one `{utt_id}.npy` (1024-d float32) per utterance in
`cache/xlsr_embeddings/`. The dual-branch training notebook expects a single
`xlsr_features.npz` with aligned arrays:

    utt_ids    (N,)      str   stable id per utterance
    splits     (N,)      str   train / dev / eval
    label_ids  (N,)      int64 0..23 for ID classes; -1 for OOD
    is_ood     (N,)      bool
    x_ssl      (N, 1024) float32

The manifest used here must be the one generated by the SSL branch
(build_manifest.py), which uses the same utt_id scheme as build_protocol_csvs.py.
One row is kept per protocol row (including the 109 wavs that the official
eval.csv lists twice), so per-split sample counts match paper Table 2 exactly;
duplicate rows simply load the same embedding.

Usage:
    python scripts/assemble_xlsr_npz.py \
        --manifest <ssl_branch>/manifests/manifest.csv \
        --cache-dir <ssl_branch>/cache/xlsr_embeddings \
        --out cache/xlsr_features.npz
"""
from __future__ import annotations

import argparse
from pathlib import Path

import numpy as np
import pandas as pd

SSL_DIM = 1024


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--manifest", required=True, type=Path)
    ap.add_argument("--cache-dir", required=True, type=Path)
    ap.add_argument("--out", required=True, type=Path)
    args = ap.parse_args()

    manifest = pd.read_csv(args.manifest).reset_index(drop=True)
    print(f"manifest: {len(manifest)} rows (protocol order; dups kept to match Table 2)")

    utt_ids = manifest["utt_id"].tolist()
    x_ssl = np.empty((len(utt_ids), SSL_DIM), dtype=np.float32)
    missing = 0
    for i, uid in enumerate(utt_ids):
        p = args.cache_dir / f"{uid}.npy"
        if not p.exists():
            missing += 1
            continue
        x_ssl[i] = np.load(p)
    if missing:
        raise SystemExit(f"ERROR: {missing} utt_ids missing from {args.cache_dir}")

    cache = {
        "utt_ids": np.array(utt_ids),
        "splits": manifest["split"].to_numpy(),
        "label_ids": manifest["class_idx"].to_numpy().astype(np.int64),
        "is_ood": manifest["is_ood"].to_numpy().astype(bool),
        "x_ssl": x_ssl,
    }
    args.out.parent.mkdir(parents=True, exist_ok=True)
    np.savez_compressed(args.out, **cache)
    print(f"wrote {args.out}  x_ssl shape {x_ssl.shape}")
    for split in ("train", "dev", "eval"):
        m = cache["splits"] == split
        is_ood = cache["is_ood"]
        print(f"  {split}: {int(m.sum())}  (ID {int(np.count_nonzero(m & ~is_ood))}, "
              f"OOD {int(np.count_nonzero(m & is_ood))})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())